import { useEffect, useState } from 'react'

const emptyTask = { title: '', description: '', priority: 'Medium', dueDate: '', status: 'todo', assignedUserId: '' }
function TaskModal({ task, users, onClose, onSave, mode = 'task' }) {
  const [form, setForm] = useState(task || emptyTask)
  const [error, setError] = useState('')
  useEffect(() => setForm(task || emptyTask), [task])
  if (mode === 'user') return <div className="modal-backdrop" role="presentation"><div className="modal"><div className="modal-heading"><div><p className="section-kicker">Team</p><h2>Add user</h2></div><button className="icon-button" onClick={onClose} type="button" aria-label="Close">×</button></div><form onSubmit={(event) => { event.preventDefault(); if (!form.name?.trim()) return setError('Name is required'); onSave({ name: form.name.trim() }) }}><label>Name<input autoFocus value={form.name || ''} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label>{error && <p className="form-error">{error}</p>}<div className="modal-actions"><button className="button button--quiet" type="button" onClick={onClose}>Cancel</button><button className="button button--primary" type="submit">Add user</button></div></form></div></div>
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }))
  return <div className="modal-backdrop" role="presentation"><div className="modal"><div className="modal-heading"><div><p className="section-kicker">{task ? 'Edit task' : 'New task'}</p><h2>{task ? 'Shape the next move' : 'Create a task'}</h2></div><button className="icon-button" onClick={onClose} type="button" aria-label="Close">×</button></div><form onSubmit={(event) => { event.preventDefault(); if (!form.title.trim()) return setError('Title is required'); if (!form.priority || !form.status) return setError('Priority and status are required'); onSave({ ...form, assignedUserId: form.assignedUserId ? Number(form.assignedUserId) : null }) }}><label>Title<input autoFocus value={form.title} onChange={(event) => set('title', event.target.value)} /></label><label>Description<textarea rows="3" value={form.description} onChange={(event) => set('description', event.target.value)} /></label><div className="form-grid"><label>Priority<select value={form.priority} onChange={(event) => set('priority', event.target.value)}><option>Low</option><option>Medium</option><option>High</option></select></label><label>Due date<input type="date" value={form.dueDate || ''} onChange={(event) => set('dueDate', event.target.value)} /></label><label>Status<select value={form.status} onChange={(event) => set('status', event.target.value)}><option value="todo">To-Do</option><option value="in_progress">In Progress</option><option value="done">Done</option></select></label><label>Assigned to<select value={form.assignedUserId || ''} onChange={(event) => set('assignedUserId', event.target.value)}><option value="">Unassigned</option>{users.map((user) => <option value={user.id} key={user.id}>{user.name}</option>)}</select></label></div>{error && <p className="form-error">{error}</p>}<div className="modal-actions"><button className="button button--quiet" type="button" onClick={onClose}>Cancel</button><button className="button button--primary" type="submit">{task ? 'Save changes' : 'Create task'}</button></div></form></div></div>
}
export default TaskModal
